---

apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "app_name.name" . }}-env-configmap
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/name: {{ template "app_name.name" . }}
data: {{ range $key, $value := .Values.environments }}
    {{ $key }}: {{ $value | quote }}{{ end }}
