apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app_name.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "app_name.name" . }}
    helm.sh/chart: {{ include "app_name.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app_name.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app_name.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: storage
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["nginx", "-g", "daemon off;"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-php
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/sbin/php-fpm7.3", "-O" ]
          ports:
            - name: fpm
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: storage
              mountPath: /web/src/var/log
              subPath: log
            - name: storage
              mountPath: /web/src/var/dumps
              subPath: dumps
          envFrom:
            - configMapRef:
                name: {{ include "app_name.name" . }}-env-configmap
          resources:
            {{- toYaml .Values.fpm.resources | nindent 12 }}
        - image: registry.example.com/library/logs-to-stdout:1.0.0
          imagePullPolicy: IfNotPresent
          name: logs-to-stdout
          volumeMounts:
            - name: storage
              mountPath: /logs
              subPath: log
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
