apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app_name.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "app_name.name" . }}
    helm.sh/chart: {{ include "app_name.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/name: {{ include "app_name.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/web/src/bin/migrate"]
          envFrom:
            - configMapRef:
                name: {{ include "app_name.name" . }}-env-configmap
