replicaCount: 1

image:
  repository: registry.example.com/app_name-release
  tag: 1.0.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
  hosts:
    - host: admin.app_name.com
      paths:
        - /
    - host: other.app_name.com
      paths:
        - /

  tls: []

nginx:
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi

fpm:
  resources:
     limits:
       cpu: 1000m
       memory: 2000Mi
     requests:
       cpu: 200m
       memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}

environments:
  BASE_DOMAIN:
  APP_ENV:
  APP_SECRET:
  DATABASE_CHARSET:
  APP_DATABASE_URL:
  APP_REDIS_URL:
  SENTRY_DSN:

